CREATE TABLE USERS (
	USER_ID BIGINT(20) NOT NULL AUTO_INCREMENT PRIMARY KEY,
	USER_FNAME VARCHAR(30) NOT NULL,
	USER_LNAME VARCHAR(30) NOT NULL,
	USER_EMAIL VARCHAR(50) NOT NULL,
	USER_CDATE DATETIME NOT NULL
);
DROP TABLE USERS;
COMMIT;
DESC USERS;

SELECT * FROM USERS;

INSERT INTO USERS (USER_FNAME, USER_LNAME, USER_EMAIL, USER_CDATE) 
  VALUES ('John', 'Doe', 'jdoe@email.com', '2011-12-18 13:17:17');
  INSERT INTO USERS (USER_FNAME, USER_LNAME, USER_EMAIL, USER_CDATE) 
  VALUES ('Aleister', 'Crowley', 'acrowley@email.com', '2011-12-18 13:17:17');